import React from 'react';
import { useNavigate } from 'react-router-dom';

const PrivacyPolicyPage: React.FC = () => {
    const navigate = useNavigate();
    return (
        <div className="min-h-screen bg-background text-foreground font-sans p-4 md:p-8 overflow-y-auto pb-24">
            <div className="max-w-4xl mx-auto bg-card p-6 md:p-10 rounded-xl shadow-lg border border-border">
                <button onClick={() => navigate(-1)} className="mb-6 text-muted-foreground hover:text-primary transition-colors flex items-center gap-2">
                    <i className="fas fa-arrow-left"></i> Back
                </button>
                <h1 className="text-3xl md:text-4xl font-bold text-primary mb-8 border-b border-border pb-4">{`Privacy Policy`}</h1>
                <h2 className="text-xl md:text-2xl font-bold text-foreground mt-8 mb-4">{`1. About this Notice`}</h2>
                <p className="mb-4 text-muted-foreground leading-relaxed" dangerouslySetInnerHTML={{ __html: `This Privacy Notice provides information on how Elddady collects and processes your personal data when you visit our website or mobile applications. It sets out what we do with your personal data and how we keep it secure and explains the rights that you have in relation to your personal data, in compliance with the Kenyan Data Protection Act and applicable international data protection laws (such as the GDPR).` }} />
                <h2 className="text-xl md:text-2xl font-bold text-foreground mt-8 mb-4">{`2. Who we are`}</h2>
                <p className="mb-4 text-muted-foreground leading-relaxed" dangerouslySetInnerHTML={{ __html: `Elddady is a leading socio-commerce platform. Our platform consists of our marketplace, which connects sellers with consumers, our logistics service, which enables the shipment and delivery of packages from sellers to consumers, and our payment service, which facilitates transactions among participants active on our platform globally, with our headquarters in Kenya. This website and/or mobile app is operated by a member of the Elddady group of companies. Any personal data provided or collected by Elddady is controlled by the subsidiary that the website and/or mobile app relates to.` }} />
                <h2 className="text-xl md:text-2xl font-bold text-foreground mt-8 mb-4">{`3. The data we collect about you`}</h2>
                <p className="mb-4 text-muted-foreground leading-relaxed" dangerouslySetInnerHTML={{ __html: `Personal data means any information that can be used to identify directly or indirectly a specific individual. We collect your personal data in order to provide tailored products and services and in order to analyse and continually improve our products and services. We may collect, use, store and transfer different kinds of personal data for marketing and personal data optimization purposes. Elddady also uses digital marketing tools to propose targeted offers for certain products and services to our customers.` }} />
                <p className="mb-4 text-muted-foreground leading-relaxed" dangerouslySetInnerHTML={{ __html: `You provide us with your personal data when you register your personal details on our website and mobile platforms and transact with the same.` }} />
                <p className="mb-4 text-muted-foreground leading-relaxed" dangerouslySetInnerHTML={{ __html: `The personal data we collect includes:` }} />
                <p className="mb-4 text-muted-foreground leading-relaxed" dangerouslySetInnerHTML={{ __html: `<strong>A. Information you provide to us:</strong> We receive and store the information you provide to us including your identity data, contact data, biometric data, delivery address and financial data. These types of personal data may include:` }} />
                <ul className="list-disc list-inside space-y-2 text-muted-foreground ml-4 mb-4">
                    <li dangerouslySetInnerHTML={{ __html: `contact details (such as your name, postal addresses, phone numbers and email addresses),` }} />
                    <li dangerouslySetInnerHTML={{ __html: `demographic information (such as your date of birth, age or age range and gender),` }} />
                    <li dangerouslySetInnerHTML={{ __html: `online registration information (such as your password and other authentication information),` }} />
                    <li dangerouslySetInnerHTML={{ __html: `payment information (such as your credit card information and billing address),` }} />
                    <li dangerouslySetInnerHTML={{ __html: `information provided as part of online questionnaires (such as responses to any customer satisfaction surveys or market research),` }} />
                    <li dangerouslySetInnerHTML={{ __html: `competition entries/submissions, and` }} />
                    <li dangerouslySetInnerHTML={{ __html: `in certain cases your marketing preferences.` }} />
                </ul>
                <p className="mb-4 text-muted-foreground leading-relaxed" dangerouslySetInnerHTML={{ __html: `<strong>B. Information we automatically collect/generate or obtain from third parties:</strong> We collect and store certain types of information regarding your use of the Elddady marketplace including information about your searches, views, downloads and purchases. In addition, we may receive information about you from third parties including our carriers; payment service providers; merchants/brands; and advertising service providers.` }} />
                <p className="mb-4 text-muted-foreground leading-relaxed" dangerouslySetInnerHTML={{ __html: `These types of personal data may relate to your device (such as your PC, tablet or other mobile device), your use of our websites and apps (as well as certain third party websites with whom we have partnered), and/or your personal preferences, interests, or geographic location. Examples of these types of information include:` }} />
                <ul className="list-disc list-inside space-y-2 text-muted-foreground ml-4 mb-4">
                    <li dangerouslySetInnerHTML={{ __html: `name and age (or predicted age range),` }} />
                    <li dangerouslySetInnerHTML={{ __html: `information about your device, operating system, browser and IP address,` }} />
                    <li dangerouslySetInnerHTML={{ __html: `unique identifiers associated with your device,` }} />
                    <li dangerouslySetInnerHTML={{ __html: `details of web pages that you have visited,` }} />
                    <li dangerouslySetInnerHTML={{ __html: `which products you have looked at online (including information about products you have searched for or viewed, purchased or added to an online shopping basket),` }} />
                    <li dangerouslySetInnerHTML={{ __html: `how long you spend on certain areas of a website or app together with the date and time of your visit/usage,` }} />
                    <li dangerouslySetInnerHTML={{ __html: `personal data contained within user-generated content (such as blogs and social media postings),` }} />
                    <li dangerouslySetInnerHTML={{ __html: `social media user name or ID, and` }} />
                    <li dangerouslySetInnerHTML={{ __html: `social media profile photo and other social media profile information (such as number of followers).` }} />
                </ul>
                <p className="mb-4 text-muted-foreground leading-relaxed" dangerouslySetInnerHTML={{ __html: `We strive to provide you with choices regarding the Personal Data that you provide to us. Where required by law, if you wish to have your Personal Data used by Elddady to provide you with a personalized experience/targeted advertising & content, you can indicate so through the relevant tick-box(es) located on the registration form or by answering the question(s) presented by Elddady representatives. If you decide that you no longer wish to benefit from this personalization, you can opt-out or adjust your preferences at any time by closing your account or by sending an email to privacy@elddady.com. You can close your account through the settings in your profile. Once your account is closed, all products and services that you access through your account will no longer be available.` }} />
                <h2 className="text-xl md:text-2xl font-bold text-foreground mt-8 mb-4">{`4. Cookies and other Identifiers`}</h2>
                <p className="mb-4 text-muted-foreground leading-relaxed" dangerouslySetInnerHTML={{ __html: `A cookie is a small file of letters and numbers that we put on your computer, mobile phone or tablet if you agree. Cookies allow us to distinguish you from other users of our website and mobile applications, which helps us to provide you with an enhanced browsing experience. For more information about cookies and how we use them, please read our Cookie Notice.` }} />
                <h2 className="text-xl md:text-2xl font-bold text-foreground mt-8 mb-4">{`5. How We Use Your Personal Data`}</h2>
                <p className="mb-4 text-muted-foreground leading-relaxed" dangerouslySetInnerHTML={{ __html: `We use your personal data to operate, provide, develop and improve the products and services that we offer, including the following:` }} />
                <p className="mb-4 text-muted-foreground leading-relaxed" dangerouslySetInnerHTML={{ __html: `<strong>A.</strong> Registering you as a new customer.` }} />
                <p className="mb-4 text-muted-foreground leading-relaxed" dangerouslySetInnerHTML={{ __html: `<strong>B.</strong> Processing and delivering your orders.` }} />
                <p className="mb-4 text-muted-foreground leading-relaxed" dangerouslySetInnerHTML={{ __html: `<strong>C.</strong> Managing your relationship with us.` }} />
                <p className="mb-4 text-muted-foreground leading-relaxed" dangerouslySetInnerHTML={{ __html: `<strong>D.</strong> Enabling you to participate in promotions, competitions and surveys.` }} />
                <p className="mb-4 text-muted-foreground leading-relaxed" dangerouslySetInnerHTML={{ __html: `<strong>E.</strong> Improving our website, applications, products and services.` }} />
                <p className="mb-4 text-muted-foreground leading-relaxed" dangerouslySetInnerHTML={{ __html: `<strong>F.</strong> Recommending/advertising products or services which may be of interest to you.` }} />
                <p className="mb-4 text-muted-foreground leading-relaxed" dangerouslySetInnerHTML={{ __html: `<strong>G.</strong> Enabling you to access certain products and services offered by our partners and vendors.` }} />
                <p className="mb-4 text-muted-foreground leading-relaxed" dangerouslySetInnerHTML={{ __html: `<strong>H.</strong> Complying with our legal obligations, including verifying your identity where necessary.` }} />
                <p className="mb-4 text-muted-foreground leading-relaxed" dangerouslySetInnerHTML={{ __html: `<strong>I.</strong> Detecting fraud.` }} />
                <h2 className="text-xl md:text-2xl font-bold text-foreground mt-8 mb-4">{`6. Legal basis for the processing of Personal Data`}</h2>
                <p className="mb-4 text-muted-foreground leading-relaxed" dangerouslySetInnerHTML={{ __html: `We will only process your personal data where we have a legal basis to do so. The legal basis will depend on the purposes for which we have collected and used your personal data. In almost every case the legal basis will be one of the following:` }} />
                <p className="mb-4 text-muted-foreground leading-relaxed" dangerouslySetInnerHTML={{ __html: `<strong>A. Consent:</strong> For example, where you have provided your consent to receive certain marketing from us. You can withdraw your consent at any time, including by clicking on the “unsubscribe” link at the bottom of any marketing email we send you.` }} />
                <p className="mb-4 text-muted-foreground leading-relaxed" dangerouslySetInnerHTML={{ __html: `<strong>B. Our legitimate business interests:</strong> Where it is necessary for us to understand our customers, promote our services and operate effectively, provided in each case that this is done in a legitimate way which does not unduly affect your privacy and other rights.` }} />
                <p className="mb-4 text-muted-foreground leading-relaxed" dangerouslySetInnerHTML={{ __html: `<strong>C. Performance of a contract with you:</strong> This would also apply where we need to take steps prior to entering into a contract with you. For example, where you have purchased a product from us and we need to use your contact details and payment information in order to process your order and send the product to you.` }} />
                <p className="mb-4 text-muted-foreground leading-relaxed" dangerouslySetInnerHTML={{ __html: `<strong>D. Compliance with law:</strong> Where we are subject to a legal obligation and need to use your personal data in order to comply with that obligation under Kenyan Law or applicable International Law.` }} />
                <h2 className="text-xl md:text-2xl font-bold text-foreground mt-8 mb-4">{`7. How We Share Your Personal Data`}</h2>
                <p className="mb-4 text-muted-foreground leading-relaxed" dangerouslySetInnerHTML={{ __html: `<strong>A. We may need to share your personal data with third parties for the following purposes:</strong>` }} />
                <ul className="list-disc list-inside space-y-2 text-muted-foreground ml-4 mb-4">
                    <li dangerouslySetInnerHTML={{ __html: `<strong>Sale of products and services:</strong> In order to deliver products and services purchased on our marketplace from third parties, we may be required to provide your personal data to such third parties.` }} />
                    <li dangerouslySetInnerHTML={{ __html: `<strong>Working with third party service providers:</strong> We engage third parties to perform certain functions on our behalf. Examples include fulfilling orders for products or services, delivering packages, analyzing data, providing marketing assistance, processing payments, transmitting content, assessing and managing credit risk, and providing customer service.` }} />
                    <li dangerouslySetInnerHTML={{ __html: `<strong>Business transfers:</strong> As we continue to develop our business, we might sell or buy other businesses or services. In such transactions, customer information may be transferred together with other business assets.` }} />
                    <li dangerouslySetInnerHTML={{ __html: `<strong>Detecting fraud and abuse:</strong> We release account and other personal data to other companies and organizations for fraud protection and credit risk reduction, and to comply with applicable law.` }} />
                </ul>
                <p className="mb-4 text-muted-foreground leading-relaxed" dangerouslySetInnerHTML={{ __html: `<strong>B. When we share your personal data with third parties we:</strong>` }} />
                <ul className="list-disc list-inside space-y-2 text-muted-foreground ml-4 mb-4">
                    <li dangerouslySetInnerHTML={{ __html: `require them to agree to use your data in accordance with the terms of this Privacy Notice, our Privacy Policy and in accordance with applicable law; and` }} />
                    <li dangerouslySetInnerHTML={{ __html: `only permit them to process your personal data for specified purposes and in accordance with our instructions. We do not allow our third-party service providers to use your personal data for their own purposes.` }} />
                </ul>
                <h2 className="text-xl md:text-2xl font-bold text-foreground mt-8 mb-4">{`8. International Transfers`}</h2>
                <p className="mb-4 text-muted-foreground leading-relaxed" dangerouslySetInnerHTML={{ __html: `We may transfer your personal data to locations in another country, if this is permissible pursuant to applicable laws in your location. There are inherent risks in such transfers.` }} />
                <p className="mb-4 text-muted-foreground leading-relaxed" dangerouslySetInnerHTML={{ __html: `In the event of international transfers of your personal data, we shall put in place measures necessary to protect your data and ensure the same level of protection available in the country of data origin, in compliance with the Kenyan Data Protection Act and international standards like the GDPR. We shall continue to respect your legal rights pursuant to the terms of this Privacy Notice and applicable laws in your location.` }} />
                <h2 className="text-xl md:text-2xl font-bold text-foreground mt-8 mb-4">{`9. Data Retention`}</h2>
                <p className="mb-4 text-muted-foreground leading-relaxed" dangerouslySetInnerHTML={{ __html: `We will take every reasonable step to ensure that your personal data is processed for the minimum period necessary for the purposes set out in this Privacy Notice. Your Personal Data may be retained in a form that allows for identification only for as long as:` }} />
                <p className="mb-4 text-muted-foreground leading-relaxed" dangerouslySetInnerHTML={{ __html: `<strong>A.</strong> We maintain an ongoing relationship with you. This will enable us to improve your experience with us and to ensure that you receive communications from us.` }} />
                <p className="mb-4 text-muted-foreground leading-relaxed" dangerouslySetInnerHTML={{ __html: `<strong>B.</strong> Your Personal Data is necessary in connection with the purposes set out in this Privacy Notice and we have a valid legal basis.` }} />
                <p className="mb-4 text-muted-foreground leading-relaxed" dangerouslySetInnerHTML={{ __html: `<strong>C.</strong> The duration of any applicable limitation period (i.e., any period during which a person could bring a legal claim against us).` }} />
                <p className="mb-4 text-muted-foreground leading-relaxed" dangerouslySetInnerHTML={{ __html: `We will actively review the personal data we hold and delete it securely, or in some cases anonymise it, when there is no longer a legal, business or consumer need for it to be retained.` }} />
                <h2 className="text-xl md:text-2xl font-bold text-foreground mt-8 mb-4">{`10. Data Security`}</h2>
                <p className="mb-4 text-muted-foreground leading-relaxed" dangerouslySetInnerHTML={{ __html: `We have put in place security measures to prevent your personal data from being accidentally lost, used or accessed in an unauthorised way, altered or disclosed. In addition, we limit access to your personal data to those employees, agents, contractors and other third parties who have a business need to know. They will only process your personal data on our instructions and they are subject to a duty of confidentiality. We have put in place procedures to deal with any suspected personal data breach and will notify you and any applicable regulator of a breach where we are legally required to do so.` }} />
                <h2 className="text-xl md:text-2xl font-bold text-foreground mt-8 mb-4">{`11. Your Legal Rights`}</h2>
                <p className="mb-4 text-muted-foreground leading-relaxed" dangerouslySetInnerHTML={{ __html: `<strong>A.</strong> It is important that the personal data we hold about you is accurate and current. Please keep us informed if your personal data changes during your relationship with us.` }} />
                <p className="mb-4 text-muted-foreground leading-relaxed" dangerouslySetInnerHTML={{ __html: `<strong>B.</strong> Under certain circumstances, you have rights under data protection laws in relation to your personal data, including the right to access, correct or erase your personal data, object to or restrict processing of your personal data, right to ask that we transfer your personal data to a third party (data portability), and unsubscribe from our emails and newsletters.` }} />
                <p className="mb-4 text-muted-foreground leading-relaxed" dangerouslySetInnerHTML={{ __html: `<strong>C.</strong> Where you wish to permanently delete your data from our website and other applications, you can choose the option of closing your account. Once your account is closed, all products and services that you access through your account will no longer be available.` }} />
                <p className="mb-4 text-muted-foreground leading-relaxed" dangerouslySetInnerHTML={{ __html: `<strong>D.</strong> We can refuse to accede to your request where it is unreasonable or where you have failed to provide additional information necessary to confirm your identity.` }} />
                <h2 className="text-xl md:text-2xl font-bold text-foreground mt-8 mb-4">{`12. Data Controllers & Contact`}</h2>
                <p className="mb-4 text-muted-foreground leading-relaxed" dangerouslySetInnerHTML={{ __html: `If you have any questions or concerns about Elddady’s Privacy Notice or you are looking for more information on how we process your personal data, or wish to exercise your legal rights in respect of your personal data, please contact the Data Privacy Officer by email at privacy@elddady.com.` }} />
                <p className="mb-4 text-muted-foreground leading-relaxed" dangerouslySetInnerHTML={{ __html: `We will investigate any complaint about the way we manage Personal Data and ensure that we respond to all substantiated complaints within prescribed timelines.` }} />
                <h2 className="text-xl md:text-2xl font-bold text-foreground mt-8 mb-4">{`13. Related Practices and Information`}</h2>
                <ul className="list-disc list-inside space-y-2 text-muted-foreground ml-4 mb-4">
                    <li dangerouslySetInnerHTML={{ __html: `Cookie Notice` }} />
                    <li dangerouslySetInnerHTML={{ __html: `Terms & Conditions` }} />
                </ul>
            </div>
        </div>
    );
};

export default PrivacyPolicyPage;