import React from 'react';
import { useNavigate } from 'react-router-dom';

const TermsAndConditionsPage: React.FC = () => {
    const navigate = useNavigate();
    return (
        <div className="min-h-screen bg-background text-foreground font-sans p-4 md:p-8 overflow-y-auto pb-24">
            <div className="max-w-4xl mx-auto bg-card p-6 md:p-10 rounded-xl shadow-lg border border-border">
                <button onClick={() => navigate(-1)} className="mb-6 text-muted-foreground hover:text-primary transition-colors flex items-center gap-2">
                    <i className="fas fa-arrow-left"></i> Back
                </button>
                <h1 className="text-3xl md:text-4xl font-bold text-primary mb-8 border-b border-border pb-4">{`Terms & Conditions`}</h1>
                <h2 className="text-xl md:text-2xl font-bold text-foreground mt-8 mb-4">{`Contents`}</h2>
                <p className="mb-4 text-muted-foreground leading-relaxed" dangerouslySetInnerHTML={{ __html: `1. Introduction` }} />
                <p className="mb-4 text-muted-foreground leading-relaxed" dangerouslySetInnerHTML={{ __html: `2. Registration and account` }} />
                <p className="mb-4 text-muted-foreground leading-relaxed" dangerouslySetInnerHTML={{ __html: `3. Terms and conditions of sale` }} />
                <p className="mb-4 text-muted-foreground leading-relaxed" dangerouslySetInnerHTML={{ __html: `4. Returns and refunds` }} />
                <p className="mb-4 text-muted-foreground leading-relaxed" dangerouslySetInnerHTML={{ __html: `5. Payments` }} />
                <p className="mb-4 text-muted-foreground leading-relaxed" dangerouslySetInnerHTML={{ __html: `6. Store credit` }} />
                <p className="mb-4 text-muted-foreground leading-relaxed" dangerouslySetInnerHTML={{ __html: `7. Promotions` }} />
                <p className="mb-4 text-muted-foreground leading-relaxed" dangerouslySetInnerHTML={{ __html: `8. Rules about your content` }} />
                <p className="mb-4 text-muted-foreground leading-relaxed" dangerouslySetInnerHTML={{ __html: `9. Our rights to use your content` }} />
                <p className="mb-4 text-muted-foreground leading-relaxed" dangerouslySetInnerHTML={{ __html: `10. Use of website and mobile applications` }} />
                <p className="mb-4 text-muted-foreground leading-relaxed" dangerouslySetInnerHTML={{ __html: `11. Copyright and trademarks` }} />
                <p className="mb-4 text-muted-foreground leading-relaxed" dangerouslySetInnerHTML={{ __html: `12. Data privacy` }} />
                <p className="mb-4 text-muted-foreground leading-relaxed" dangerouslySetInnerHTML={{ __html: `13. Due diligence and audit rights` }} />
                <p className="mb-4 text-muted-foreground leading-relaxed" dangerouslySetInnerHTML={{ __html: `14. Elddady’s role as a marketplace` }} />
                <p className="mb-4 text-muted-foreground leading-relaxed" dangerouslySetInnerHTML={{ __html: `15. Limitations and exclusions of liability` }} />
                <p className="mb-4 text-muted-foreground leading-relaxed" dangerouslySetInnerHTML={{ __html: `16. Indemnification` }} />
                <p className="mb-4 text-muted-foreground leading-relaxed" dangerouslySetInnerHTML={{ __html: `17. Breaches of these general terms and conditions` }} />
                <p className="mb-4 text-muted-foreground leading-relaxed" dangerouslySetInnerHTML={{ __html: `18. Entire agreement` }} />
                <p className="mb-4 text-muted-foreground leading-relaxed" dangerouslySetInnerHTML={{ __html: `19. Hierarchy` }} />
                <p className="mb-4 text-muted-foreground leading-relaxed" dangerouslySetInnerHTML={{ __html: `20. Variation` }} />
                <p className="mb-4 text-muted-foreground leading-relaxed" dangerouslySetInnerHTML={{ __html: `21. No waiver` }} />
                <p className="mb-4 text-muted-foreground leading-relaxed" dangerouslySetInnerHTML={{ __html: `22. Severability` }} />
                <p className="mb-4 text-muted-foreground leading-relaxed" dangerouslySetInnerHTML={{ __html: `23. Assignment` }} />
                <p className="mb-4 text-muted-foreground leading-relaxed" dangerouslySetInnerHTML={{ __html: `24. Third party rights` }} />
                <p className="mb-4 text-muted-foreground leading-relaxed" dangerouslySetInnerHTML={{ __html: `25. Law and jurisdiction` }} />
                <p className="mb-4 text-muted-foreground leading-relaxed" dangerouslySetInnerHTML={{ __html: `26. Our company details and notices` }} />
                <h2 className="text-xl md:text-2xl font-bold text-foreground mt-8 mb-4">{`1. Introduction`}</h2>
                <p className="mb-4 text-muted-foreground leading-relaxed" dangerouslySetInnerHTML={{ __html: `1.1 "Elddady" is the trading name for the Elddady group companies. Each Elddady group company (“Elddady” or “we”) operates a socio-commerce platform consisting of a website and mobile application (“marketplace”), together with supporting IT, logistics and payment infrastructure, for the sale and purchase of consumer products and services (“products”) globally, with its headquarters based in Kenya.` }} />
                <p className="mb-4 text-muted-foreground leading-relaxed" dangerouslySetInnerHTML={{ __html: `1.2 These general terms and conditions shall apply to buyers and sellers on the marketplace and shall govern your use of the marketplace and related services.` }} />
                <p className="mb-4 text-muted-foreground leading-relaxed" dangerouslySetInnerHTML={{ __html: `1.3 By using our marketplace, you accept these general terms and conditions in full. If you disagree with these general terms and conditions or any part of these general terms and conditions, you must not use our marketplace.` }} />
                <p className="mb-4 text-muted-foreground leading-relaxed" dangerouslySetInnerHTML={{ __html: `1.4 If you use our marketplace in the course of a business or other organizational project, then by so doing you:` }} />
                <p className="mb-4 text-muted-foreground leading-relaxed" dangerouslySetInnerHTML={{ __html: `1.4.1 confirm that you have obtained the necessary authority to agree to these general terms and conditions;` }} />
                <p className="mb-4 text-muted-foreground leading-relaxed" dangerouslySetInnerHTML={{ __html: `1.4.2 bind both yourself and the person, company or other legal entity that operates that business or organizational project, to these general terms and conditions; and` }} />
                <p className="mb-4 text-muted-foreground leading-relaxed" dangerouslySetInnerHTML={{ __html: `1.4.3 agree that "you" in these general terms and conditions shall reference both the individual user and the relevant person, company or legal entity unless the context requires otherwise.` }} />
                <h2 className="text-xl md:text-2xl font-bold text-foreground mt-8 mb-4">{`2. Registration and account`}</h2>
                <p className="mb-4 text-muted-foreground leading-relaxed" dangerouslySetInnerHTML={{ __html: `2.1 You may not register with our marketplace if you are under 18 years of age (by using our marketplace or agreeing to these general terms and conditions, you warrant and represent to us that you are at least 18 years of age).` }} />
                <p className="mb-4 text-muted-foreground leading-relaxed" dangerouslySetInnerHTML={{ __html: `2.2 If you register for an account with our marketplace, you will be asked to provide an email address/user ID and password and you agree to:` }} />
                <p className="mb-4 text-muted-foreground leading-relaxed" dangerouslySetInnerHTML={{ __html: `2.2.1 keep your password confidential;` }} />
                <p className="mb-4 text-muted-foreground leading-relaxed" dangerouslySetInnerHTML={{ __html: `2.2.2 notify us in writing immediately (using our contact details provided at section 26) if you become aware of any disclosure of your password; and` }} />
                <p className="mb-4 text-muted-foreground leading-relaxed" dangerouslySetInnerHTML={{ __html: `2.2.3 be responsible for any activity on our marketplace arising out of any failure to keep your password confidential, and you acknowledge that you may be held liable for any losses arising out of such a failure.` }} />
                <p className="mb-4 text-muted-foreground leading-relaxed" dangerouslySetInnerHTML={{ __html: `2.3 Your account shall be used exclusively by you and you shall not transfer your account to any third party. If you authorize any third party to manage your account on your behalf this shall be at your own risk.` }} />
                <p className="mb-4 text-muted-foreground leading-relaxed" dangerouslySetInnerHTML={{ __html: `2.4 We may suspend or cancel your account, and/or edit your account details, at any time in our sole discretion and without notice or explanation, providing that if we cancel any products or services you have paid for but not received, and you have not breached these general terms and conditions, we will refund you in respect of the same. See section 4.2 below for further information about refunds.` }} />
                <p className="mb-4 text-muted-foreground leading-relaxed" dangerouslySetInnerHTML={{ __html: `2.5 You may cancel your account on our marketplace by contacting us as provided at section 26.` }} />
                <h2 className="text-xl md:text-2xl font-bold text-foreground mt-8 mb-4">{`3. Terms and conditions of sale`}</h2>
                <p className="mb-4 text-muted-foreground leading-relaxed" dangerouslySetInnerHTML={{ __html: `3.1 You acknowledge and agree that:` }} />
                <p className="mb-4 text-muted-foreground leading-relaxed" dangerouslySetInnerHTML={{ __html: `3.1.1 the marketplace provides an online location for sellers to sell and buyers to purchase products;` }} />
                <p className="mb-4 text-muted-foreground leading-relaxed" dangerouslySetInnerHTML={{ __html: `3.1.2 we shall accept binding sales, on behalf of sellers, but (unless Elddady is indicated as the seller) Elddady is not a party to the transaction between the seller and the buyer; and` }} />
                <p className="mb-4 text-muted-foreground leading-relaxed" dangerouslySetInnerHTML={{ __html: `3.1.3 a contract for the sale and purchase of a product or products will come into force between the buyer and seller, and accordingly you commit to buying or selling the relevant product or products, upon the buyer’s confirmation of purchase via the marketplace.` }} />
                <p className="mb-4 text-muted-foreground leading-relaxed" dangerouslySetInnerHTML={{ __html: `3.2 Subject to these general terms and conditions, the seller’s terms of business shall govern the contract for sale and purchase between the buyer and the seller. Notwithstanding this, the following provisions will be incorporated into the contract of sale and purchase between the buyer and the seller:` }} />
                <p className="mb-4 text-muted-foreground leading-relaxed" dangerouslySetInnerHTML={{ __html: `3.2.1 the price for a product will be as stated in the relevant product listing;` }} />
                <p className="mb-4 text-muted-foreground leading-relaxed" dangerouslySetInnerHTML={{ __html: `3.2.2 the price for the product must include all taxes and comply with applicable laws in force from time to time;` }} />
                <p className="mb-4 text-muted-foreground leading-relaxed" dangerouslySetInnerHTML={{ __html: `3.2.3 delivery charges, packaging charges, handling charges, administrative charges, insurance costs, other ancillary costs and charges, where applicable, will only be payable by the buyer if this is expressly and clearly stated in the product listing; and delivery of digital products may be made electronically;` }} />
                <p className="mb-4 text-muted-foreground leading-relaxed" dangerouslySetInnerHTML={{ __html: `3.2.4 products must be of satisfactory quality, fit and safe for any purpose specified in, and conform in all material respects to, the product listing and any other description of the products supplied or made available by the seller to the buyer; and` }} />
                <p className="mb-4 text-muted-foreground leading-relaxed" dangerouslySetInnerHTML={{ __html: `3.2.5 in respect of physical products sold, the seller warrants that the seller has good title to, and is the sole legal and beneficial owner of, the products and/or has the right to supply the products pursuant to this agreement, and that the products are not subject to any third party rights or restrictions including in respect of third party intellectual property rights and/or any criminal, insolvency or tax investigation or proceedings; and in respect of digital products the seller warrants that the seller has the right to supply the digital products to the buyer.` }} />
                <p className="mb-4 text-muted-foreground leading-relaxed" dangerouslySetInnerHTML={{ __html: `3.2.6 The Seller warrants that, where a product sold has such terms, the Seller will provide detailed disclosure of the product terms and conditions, any applicable warranty, and other terms necessary to inform the buyer on the product and its usage in the specification section provided on each product page.` }} />
                <h2 className="text-xl md:text-2xl font-bold text-foreground mt-8 mb-4">{`4. Returns and refunds`}</h2>
                <p className="mb-4 text-muted-foreground leading-relaxed" dangerouslySetInnerHTML={{ __html: `4.1 Returns of products by buyers and acceptance of returned products by sellers shall be managed by us in accordance with the returns page on the marketplace, as may be amended from time to time. Acceptance of returns shall be in our discretion, subject to compliance with applicable laws of the territory.` }} />
                <p className="mb-4 text-muted-foreground leading-relaxed" dangerouslySetInnerHTML={{ __html: `4.2 Refunds in respect of returned products shall be managed in accordance with the refunds page on the marketplace, as may be amended from time to time. Our rules on refunds shall be exercised in our discretion, subject to applicable laws of the territory. We may offer refunds, in our discretion:` }} />
                <p className="mb-4 text-muted-foreground leading-relaxed" dangerouslySetInnerHTML={{ __html: `4.2.1 in respect of the product price;` }} />
                <p className="mb-4 text-muted-foreground leading-relaxed" dangerouslySetInnerHTML={{ __html: `4.2.2 in respect of local and/or international shipping fees (as stated on the refunds page); and` }} />
                <p className="mb-4 text-muted-foreground leading-relaxed" dangerouslySetInnerHTML={{ __html: `4.2.3 by way of store credits, vouchers, mobile money transfer, bank transfers or such other methods as we may determine from time to time.` }} />
                <p className="mb-4 text-muted-foreground leading-relaxed" dangerouslySetInnerHTML={{ __html: `4.3 Returned products shall be accepted and refunds issued by Elddady, acting for and on behalf of the seller. Notwithstanding paragraphs 4.1 and 4.2 above, in respect of digital products or services and fresh food, Elddady shall issue refunds in respect of failures in delivery only. Refunds of payment for such products for any other reasons shall be subject to the seller’s terms and conditions of sale.` }} />
                <p className="mb-4 text-muted-foreground leading-relaxed" dangerouslySetInnerHTML={{ __html: `4.4 Changes to our returns page or refunds page shall be effective in respect of all purchases made from the date of publication of the change on our website.` }} />
                <h2 className="text-xl md:text-2xl font-bold text-foreground mt-8 mb-4">{`5. Payments`}</h2>
                <p className="mb-4 text-muted-foreground leading-relaxed" dangerouslySetInnerHTML={{ __html: `5.1 You must make payments due under these general terms and conditions in accordance with the Payments Information and Guidelines on the marketplace.` }} />
                <h2 className="text-xl md:text-2xl font-bold text-foreground mt-8 mb-4">{`6. Store credit`}</h2>
                <p className="mb-4 text-muted-foreground leading-relaxed" dangerouslySetInnerHTML={{ __html: `6.1 Store credits may be earned and managed in accordance with the Elddady Store Credit Terms and Conditions, as may be amended from time to time. Elddady reserves the right to cancel or withdraw Elddady store credit rewards for any reason in its discretion, including if we suspect fraud or foul play. You can view the Elddady Store Credit terms and conditions and information about your Elddady store credit account on our website and mobile application.` }} />
                <h2 className="text-xl md:text-2xl font-bold text-foreground mt-8 mb-4">{`7. Promotions`}</h2>
                <p className="mb-4 text-muted-foreground leading-relaxed" dangerouslySetInnerHTML={{ __html: `7.1 Promotions and competitions run by Elddady and/or other promoters shall be managed in accordance with the Promotions Terms and Conditions, where applicable. You can view Promotions Terms and Conditions where they apply on our website or mobile application` }} />
                <h2 className="text-xl md:text-2xl font-bold text-foreground mt-8 mb-4">{`8. Rules about your content`}</h2>
                <p className="mb-4 text-muted-foreground leading-relaxed" dangerouslySetInnerHTML={{ __html: `8.1 In these general terms and conditions, "your content" means:` }} />
                <p className="mb-4 text-muted-foreground leading-relaxed" dangerouslySetInnerHTML={{ __html: `8.1.1 all works and materials (including without limitation text, graphics, images, audio material, video material, audio-visual material, scripts, software and files) that you submit to us or our marketplace for storage or publication, processing by, or onward transmission; and` }} />
                <p className="mb-4 text-muted-foreground leading-relaxed" dangerouslySetInnerHTML={{ __html: `8.1.2 all communications on the marketplace, including product reviews, feedback and comments.` }} />
                <p className="mb-4 text-muted-foreground leading-relaxed" dangerouslySetInnerHTML={{ __html: `8.2 Your content, and the use of your content by us in accordance with these general terms and conditions, must be accurate, complete and truthful.` }} />
                <p className="mb-4 text-muted-foreground leading-relaxed" dangerouslySetInnerHTML={{ __html: `8.3 Your content must be appropriate, civil and tasteful, and accord with generally accepted standards of etiquette and behaviour on the internet, and must not:` }} />
                <p className="mb-4 text-muted-foreground leading-relaxed" dangerouslySetInnerHTML={{ __html: `8.3.1 be offensive, obscene, indecent, pornographic, lewd, suggestive or sexually explicit;` }} />
                <p className="mb-4 text-muted-foreground leading-relaxed" dangerouslySetInnerHTML={{ __html: `8.3.2 depict violence in an explicit, graphic or gratuitous manner; or` }} />
                <p className="mb-4 text-muted-foreground leading-relaxed" dangerouslySetInnerHTML={{ __html: `8.3.3 be blasphemous, in breach of racial or religious hatred or discrimination legislation;` }} />
                <p className="mb-4 text-muted-foreground leading-relaxed" dangerouslySetInnerHTML={{ __html: `8.3.4 be deceptive, fraudulent, threatening, abusive, harassing, anti-social, menacing, hateful, discriminatory or inflammatory;` }} />
                <p className="mb-4 text-muted-foreground leading-relaxed" dangerouslySetInnerHTML={{ __html: `8.3.5 cause annoyance, inconvenience or needless anxiety to any person; or` }} />
                <p className="mb-4 text-muted-foreground leading-relaxed" dangerouslySetInnerHTML={{ __html: `8.3.6 constitute spam` }} />
                <p className="mb-4 text-muted-foreground leading-relaxed" dangerouslySetInnerHTML={{ __html: `8.4 Your content must not be illegal or unlawful, infringe any person's legal rights, or be capable of giving rise to legal action against any person (in each case in any jurisdiction and under any applicable law). Your content must not infringe or breach:` }} />
                <p className="mb-4 text-muted-foreground leading-relaxed" dangerouslySetInnerHTML={{ __html: `8.4.1 any copyright, moral right, database right, trademark right, design right, right in passing off or other intellectual property right;` }} />
                <p className="mb-4 text-muted-foreground leading-relaxed" dangerouslySetInnerHTML={{ __html: `8.4.2 any right of confidence, right of privacy or right under data protection legislation;` }} />
                <p className="mb-4 text-muted-foreground leading-relaxed" dangerouslySetInnerHTML={{ __html: `8.4.5 any contractual obligation owed to any person; or` }} />
                <p className="mb-4 text-muted-foreground leading-relaxed" dangerouslySetInnerHTML={{ __html: `8.4.6 any court order.` }} />
                <p className="mb-4 text-muted-foreground leading-relaxed" dangerouslySetInnerHTML={{ __html: `8.5 You must not use our marketplace to link to any website or web page consisting of or containing material that would, were it posted on our marketplace, breach the provisions of these general terms and conditions.` }} />
                <p className="mb-4 text-muted-foreground leading-relaxed" dangerouslySetInnerHTML={{ __html: `8.6 You must not submit to our marketplace any material that is or has ever been the subject of any threatened or actual legal proceedings or other similar complaint.` }} />
                <p className="mb-4 text-muted-foreground leading-relaxed" dangerouslySetInnerHTML={{ __html: `8.7 The review function on the marketplace may be used to facilitate buyer reviews on products. You shall not use the review function or any other form of communication to provide inaccurate, inauthentic or fake reviews.` }} />
                <p className="mb-4 text-muted-foreground leading-relaxed" dangerouslySetInnerHTML={{ __html: `8.8 You must not interfere with a transaction by: (i) contacting another user to buy or sell an item listed on the marketplace outside of the marketplace; or (ii) communicating with a user involved in an active or completed transaction to warn them away from a particular buyer, seller or item; or (iii) contacting another user with the intent to collect any payments` }} />
                <p className="mb-4 text-muted-foreground leading-relaxed" dangerouslySetInnerHTML={{ __html: `8.9 You acknowledge that all users of the marketplace are solely responsible for interactions with other users and you shall exercise caution and good judgment in your communication with users. You shall not send them personal information including credit card details.` }} />
                <p className="mb-4 text-muted-foreground leading-relaxed" dangerouslySetInnerHTML={{ __html: `8.10 We may periodically review your content and we reserve the right to remove any content in our discretion for any reason whatsoever.` }} />
                <p className="mb-4 text-muted-foreground leading-relaxed" dangerouslySetInnerHTML={{ __html: `8.11 If you learn of any unlawful material or activity on our marketplace, or any material or activity that breaches these general terms and conditions, you may inform us by contacting us as provided at section 26.` }} />
                <h2 className="text-xl md:text-2xl font-bold text-foreground mt-8 mb-4">{`9. Our rights to use your content`}</h2>
                <p className="mb-4 text-muted-foreground leading-relaxed" dangerouslySetInnerHTML={{ __html: `9.1 You grant to us a worldwide, irrevocable, non-exclusive, royalty-free license to use, reproduce, store, adapt, publish, translate and distribute your content on our marketplace, and across our marketing channels and any existing or future media.` }} />
                <p className="mb-4 text-muted-foreground leading-relaxed" dangerouslySetInnerHTML={{ __html: `9.2 You grant to us the right to sub-license the rights licensed under section 9.1.` }} />
                <p className="mb-4 text-muted-foreground leading-relaxed" dangerouslySetInnerHTML={{ __html: `9.3 You grant to us the right to bring an action for infringement of the rights licensed under section 9.1.` }} />
                <p className="mb-4 text-muted-foreground leading-relaxed" dangerouslySetInnerHTML={{ __html: `9.4 You hereby waive all your moral rights in your content to the maximum extent permitted by applicable law; and you warrant and represent that all other moral rights in your content have been waived to the maximum extent permitted by applicable law.` }} />
                <p className="mb-4 text-muted-foreground leading-relaxed" dangerouslySetInnerHTML={{ __html: `9.5 Without prejudice to our other rights under these general terms and conditions, if you breach our rules on content in any way, or if we reasonably suspect that you have breached our rules on content, we may delete, unpublish or edit any or all of your content.` }} />
                <h2 className="text-xl md:text-2xl font-bold text-foreground mt-8 mb-4">{`10. Use of website and mobile applications`}</h2>
                <p className="mb-4 text-muted-foreground leading-relaxed" dangerouslySetInnerHTML={{ __html: `10.1 In this section 10 words “marketplace” and "website” shall be used interchangeably to refer to Elddady’s websites and mobile applications.` }} />
                <p className="mb-4 text-muted-foreground leading-relaxed" dangerouslySetInnerHTML={{ __html: `10.2 You may:` }} />
                <p className="mb-4 text-muted-foreground leading-relaxed" dangerouslySetInnerHTML={{ __html: `10.2.1 view pages from our website in a web browser;` }} />
                <p className="mb-4 text-muted-foreground leading-relaxed" dangerouslySetInnerHTML={{ __html: `10.2.2 download pages from our website for caching in a web browser;` }} />
                <p className="mb-4 text-muted-foreground leading-relaxed" dangerouslySetInnerHTML={{ __html: `10.2.3 print pages from our website for your own personal and non-commercial use, providing that such printing is not systematic or excessive;` }} />
                <p className="mb-4 text-muted-foreground leading-relaxed" dangerouslySetInnerHTML={{ __html: `10.2.4 stream audio and video files from our website using the media player on our website; and` }} />
                <p className="mb-4 text-muted-foreground leading-relaxed" dangerouslySetInnerHTML={{ __html: `10.2.5 use our marketplace services by means of a web browser,` }} />
                <p className="mb-4 text-muted-foreground leading-relaxed" dangerouslySetInnerHTML={{ __html: `subject to the other provisions of these general terms and conditions.` }} />
                <p className="mb-4 text-muted-foreground leading-relaxed" dangerouslySetInnerHTML={{ __html: `10.3 Except as expressly permitted by section 10.2 or the other provisions of these general terms and conditions, you must not download any material from our website or save any such material to your computer.` }} />
                <p className="mb-4 text-muted-foreground leading-relaxed" dangerouslySetInnerHTML={{ __html: `10.4 You may only use our website for your own personal and business purposes in respect of selling or purchasing products on the marketplace.` }} />
                <p className="mb-4 text-muted-foreground leading-relaxed" dangerouslySetInnerHTML={{ __html: `10.5 Except as expressly permitted by these general terms and conditions, you must not edit or otherwise modify any material on our website.` }} />
                <p className="mb-4 text-muted-foreground leading-relaxed" dangerouslySetInnerHTML={{ __html: `10.6 Unless you own or control the relevant rights in the material, you must not:` }} />
                <p className="mb-4 text-muted-foreground leading-relaxed" dangerouslySetInnerHTML={{ __html: `10.6.1 republish material from our website (including republication on another website);` }} />
                <p className="mb-4 text-muted-foreground leading-relaxed" dangerouslySetInnerHTML={{ __html: `10.6.2 sell, rent or sub-license material from our website;` }} />
                <p className="mb-4 text-muted-foreground leading-relaxed" dangerouslySetInnerHTML={{ __html: `10.6.3 show any material from our website in public;` }} />
                <p className="mb-4 text-muted-foreground leading-relaxed" dangerouslySetInnerHTML={{ __html: `10.6.4 exploit material from our website for a commercial purpose; or` }} />
                <p className="mb-4 text-muted-foreground leading-relaxed" dangerouslySetInnerHTML={{ __html: `10.6.5 redistribute material from our website.` }} />
                <p className="mb-4 text-muted-foreground leading-relaxed" dangerouslySetInnerHTML={{ __html: `10.7 Notwithstanding section 10.6, you may forward links to products on our website and redistribute our newsletter and promotional materials in print and electronic form to any person.` }} />
                <p className="mb-4 text-muted-foreground leading-relaxed" dangerouslySetInnerHTML={{ __html: `10.8 We reserve the right to suspend or restrict access to our website, to areas of our website and/or to functionality upon our website. We may, for example, suspend access to the website during server maintenance or when we update the website. You must not circumvent or bypass, or attempt to circumvent or bypass, any access restriction measures on the website.` }} />
                <p className="mb-4 text-muted-foreground leading-relaxed" dangerouslySetInnerHTML={{ __html: `10.9 You must not:` }} />
                <p className="mb-4 text-muted-foreground leading-relaxed" dangerouslySetInnerHTML={{ __html: `10.9.1 use our website in any way or take any action that causes, or may cause, damage to the website or impairment of the performance, availability, accessibility, integrity or security of the website;` }} />
                <p className="mb-4 text-muted-foreground leading-relaxed" dangerouslySetInnerHTML={{ __html: `10.9.2 use our website in any way that is unethical, unlawful, illegal, fraudulent or harmful, or in connection with any unlawful, illegal, fraudulent or harmful purpose or activity;` }} />
                <p className="mb-4 text-muted-foreground leading-relaxed" dangerouslySetInnerHTML={{ __html: `10.9.3 hack or otherwise tamper with our website;` }} />
                <p className="mb-4 text-muted-foreground leading-relaxed" dangerouslySetInnerHTML={{ __html: `10.9.4 probe, scan or test the vulnerability of our website without our permission;` }} />
                <p className="mb-4 text-muted-foreground leading-relaxed" dangerouslySetInnerHTML={{ __html: `10.9.5 circumvent any authentication or security systems or processes on or relating to our website;` }} />
                <p className="mb-4 text-muted-foreground leading-relaxed" dangerouslySetInnerHTML={{ __html: `10.9.6 use our website to copy, store, host, transmit, send, use, publish or distribute any material which consists of (or is linked to) any spyware, computer virus, Trojan horse, worm, keystroke logger, rootkit or other malicious computer software;` }} />
                <p className="mb-4 text-muted-foreground leading-relaxed" dangerouslySetInnerHTML={{ __html: `10.9.7 impose an unreasonably large load on our website resources (including bandwidth, storage capacity and processing capacity);` }} />
                <p className="mb-4 text-muted-foreground leading-relaxed" dangerouslySetInnerHTML={{ __html: `10.9.8 decrypt or decipher any communications sent by or to our website without our permission;` }} />
                <p className="mb-4 text-muted-foreground leading-relaxed" dangerouslySetInnerHTML={{ __html: `10.9.9 conduct any systematic or automated data collection activities (including without limitation scraping, data mining, data extraction and data harvesting) on or in relation to our website without our express written consent;` }} />
                <p className="mb-4 text-muted-foreground leading-relaxed" dangerouslySetInnerHTML={{ __html: `10.9.10 access or otherwise interact with our website using any robot, spider or other automated means, except for the purpose of search engine indexing;` }} />
                <p className="mb-4 text-muted-foreground leading-relaxed" dangerouslySetInnerHTML={{ __html: `10.9.11 use our website except by means of our public interfaces;` }} />
                <p className="mb-4 text-muted-foreground leading-relaxed" dangerouslySetInnerHTML={{ __html: `10.9.12 violate the directives set out in the robots.txt file for our website;` }} />
                <p className="mb-4 text-muted-foreground leading-relaxed" dangerouslySetInnerHTML={{ __html: `10.9.12 use data collected from our website for any direct marketing activity (including without limitation email marketing, SMS marketing, telemarketing and direct mailing); or` }} />
                <p className="mb-4 text-muted-foreground leading-relaxed" dangerouslySetInnerHTML={{ __html: `10.9.13 do anything that interferes with the normal use of our website.` }} />
                <h2 className="text-xl md:text-2xl font-bold text-foreground mt-8 mb-4">{`11. Copyright and trademarks`}</h2>
                <p className="mb-4 text-muted-foreground leading-relaxed" dangerouslySetInnerHTML={{ __html: `11.1 Subject to the express provisions of these general terms and conditions:` }} />
                <p className="mb-4 text-muted-foreground leading-relaxed" dangerouslySetInnerHTML={{ __html: `11.1.1 we, together with our licensors, own and control all the copyright and other intellectual property rights in our website and the material on our website; and` }} />
                <p className="mb-4 text-muted-foreground leading-relaxed" dangerouslySetInnerHTML={{ __html: `11.1.2 all the copyright and other intellectual property rights in our website and the material on our website are reserved.` }} />
                <p className="mb-4 text-muted-foreground leading-relaxed" dangerouslySetInnerHTML={{ __html: `11.2 Elddady’s logos and our other registered and unregistered trademarks are trademarks belonging to us; we give no permission for the use of these trademarks, and such use may constitute an infringement of our rights.` }} />
                <p className="mb-4 text-muted-foreground leading-relaxed" dangerouslySetInnerHTML={{ __html: `11.3 The third party registered and unregistered trademarks or service marks on our website are the property of their respective owners and we do not endorse and are not affiliated with any of the holders of any such rights and as such we cannot grant any license to exercise such rights.` }} />
                <h2 className="text-xl md:text-2xl font-bold text-foreground mt-8 mb-4">{`12. Data privacy`}</h2>
                <p className="mb-4 text-muted-foreground leading-relaxed" dangerouslySetInnerHTML={{ __html: `12.1 Buyers agree to processing of their personal data in accordance with the terms of Elddady’s Privacy Notice and Cookie Notice.` }} />
                <p className="mb-4 text-muted-foreground leading-relaxed" dangerouslySetInnerHTML={{ __html: `12.2 Elddady shall process all personal data obtained through the marketplace and related services in accordance with the terms of our Privacy Notice and Cookie Notice and Privacy Policy.` }} />
                <p className="mb-4 text-muted-foreground leading-relaxed" dangerouslySetInnerHTML={{ __html: `12.3 Sellers shall be directly responsible to buyers for any misuse of their personal data and Elddady shall bear no liability to buyers in respect of any misuse by sellers of their personal data.` }} />
                <h2 className="text-xl md:text-2xl font-bold text-foreground mt-8 mb-4">{`13. Due diligence and audit rights`}</h2>
                <p className="mb-4 text-muted-foreground leading-relaxed" dangerouslySetInnerHTML={{ __html: `13.1 We operate an anti-fraud and anti-money laundering compliance program and reserve the right to perform due diligence checks on all users of the marketplace.` }} />
                <p className="mb-4 text-muted-foreground leading-relaxed" dangerouslySetInnerHTML={{ __html: `13.2 You agree to provide to us all such information, documentation and access to your business premises as we may require:` }} />
                <p className="mb-4 text-muted-foreground leading-relaxed" dangerouslySetInnerHTML={{ __html: `13.2.1 in order to verify your adherence to, and performance of, your obligations under these terms and conditions;` }} />
                <p className="mb-4 text-muted-foreground leading-relaxed" dangerouslySetInnerHTML={{ __html: `13.2.2 for the purpose of disclosures pursuant to a valid order by a court or other governmental body; or` }} />
                <p className="mb-4 text-muted-foreground leading-relaxed" dangerouslySetInnerHTML={{ __html: `13.2.3 as otherwise required by law or applicable regulation.` }} />
                <h2 className="text-xl md:text-2xl font-bold text-foreground mt-8 mb-4">{`14. Elddady’s role as a marketplace`}</h2>
                <p className="mb-4 text-muted-foreground leading-relaxed" dangerouslySetInnerHTML={{ __html: `14.1 You acknowledge that:` }} />
                <p className="mb-4 text-muted-foreground leading-relaxed" dangerouslySetInnerHTML={{ __html: `14.1.1 Elddady facilitates a marketplace for buyers and third party sellers or Elddady, where Elddady is the seller of a product;` }} />
                <p className="mb-4 text-muted-foreground leading-relaxed" dangerouslySetInnerHTML={{ __html: `14.1.2 the relevant seller of the product (whether Elddady is the seller or whether it is a third party seller) shall at all times remain exclusively liable for the products they sell on the marketplace; and` }} />
                <p className="mb-4 text-muted-foreground leading-relaxed" dangerouslySetInnerHTML={{ __html: `14.1.3 in the event that there is an issue arising from the purchase of a product on the marketplace, the buyer should seek recourse from the relevant seller of the product by following the process set out in Elddady’s Dispute Resolution Policy .` }} />
                <p className="mb-4 text-muted-foreground leading-relaxed" dangerouslySetInnerHTML={{ __html: `14.2 We commit to ensure that Elddady, or third party sellers, as applicable, submit information relating to their products on the marketplace that is complete, accurate and up to date and pursuant thereto:` }} />
                <p className="mb-4 text-muted-foreground leading-relaxed" dangerouslySetInnerHTML={{ __html: `14.2.1 the relevant seller warrants and represents the completeness and accuracy of their information published on our marketplace relating to their products;` }} />
                <p className="mb-4 text-muted-foreground leading-relaxed" dangerouslySetInnerHTML={{ __html: `14.2.2 the relevant seller warrants and represents that the material on the marketplace is up to date; and` }} />
                <p className="mb-4 text-muted-foreground leading-relaxed" dangerouslySetInnerHTML={{ __html: `14.2.3 if a buyer has a complaint relating to the accuracy or completeness of the product information received from a seller (including where Elddady is the seller), the buyer can seek recourse from the relevant seller by following the process set out in the Elddady’s Dispute Resolution Policy.` }} />
                <p className="mb-4 text-muted-foreground leading-relaxed" dangerouslySetInnerHTML={{ __html: `14.3 We do not warrant or represent that the marketplace will operate without fault; or that the marketplace or any service on the marketplace will remain available during the occurrence of events beyond Elddady’s control (force majeure events) which include but are not limited to; flood, drought, earthquake or other natural disasters; hacking, viruses, malware or other malicious software attacks on the marketplace; terrorist attacks, civil war, civil commotion or riots; war, threat of or preparation for war; epidemics or pandemics; or extra-constitutional events or circumstances which materially and adversely affect the political or macro-economic stability of the territory as a whole.` }} />
                <p className="mb-4 text-muted-foreground leading-relaxed" dangerouslySetInnerHTML={{ __html: `14.4 We reserve the right to discontinue or alter any or all of our marketplace services, and to stop publishing our marketplace, at any time in our sole discretion without notice or explanation; and you will not be entitled to any compensation or other payment upon the discontinuance or alteration of any marketplace services, or if we stop publishing the marketplace. This is without prejudice to your rights in respect of any unfulfilled orders or other existing liabilities of Elddady.` }} />
                <p className="mb-4 text-muted-foreground leading-relaxed" dangerouslySetInnerHTML={{ __html: `14.5 If we discontinue or alter any or all of our marketplace in circumstances not relating to force majeure, we will provide prior notice to the buyers and sellers of not less than fifteen (15) days with clear guidance on the way forward for the pending transactions or other existing liabilities of Elddady.` }} />
                <p className="mb-4 text-muted-foreground leading-relaxed" dangerouslySetInnerHTML={{ __html: `14.6 We do not guarantee any commercial results concerning the use of the marketplace.` }} />
                <p className="mb-4 text-muted-foreground leading-relaxed" dangerouslySetInnerHTML={{ __html: `14.7 To the maximum extent permitted by applicable law and subject to section 15.1 below, we exclude all representations and warranties relating to the subject matter of these general terms and conditions, our marketplace and the use of our marketplace.` }} />
                <h2 className="text-xl md:text-2xl font-bold text-foreground mt-8 mb-4">{`15. Limitations and exclusions of liability`}</h2>
                <p className="mb-4 text-muted-foreground leading-relaxed" dangerouslySetInnerHTML={{ __html: `15.1 Nothing in these general terms and conditions will:` }} />
                <p className="mb-4 text-muted-foreground leading-relaxed" dangerouslySetInnerHTML={{ __html: `15.1.1 limit any liabilities in any way that is not permitted under applicable law; or` }} />
                <p className="mb-4 text-muted-foreground leading-relaxed" dangerouslySetInnerHTML={{ __html: `15.1.2 exclude any liabilities or statutory rights that may not be excluded under applicable law` }} />
                <p className="mb-4 text-muted-foreground leading-relaxed" dangerouslySetInnerHTML={{ __html: `15.2 The limitations and exclusions of liability set out in this section 15 and elsewhere in these general terms and conditions:` }} />
                <p className="mb-4 text-muted-foreground leading-relaxed" dangerouslySetInnerHTML={{ __html: `15.2.1 are subject to section 15.1; and` }} />
                <p className="mb-4 text-muted-foreground leading-relaxed" dangerouslySetInnerHTML={{ __html: `15.2.2 govern all liabilities arising under these general terms and conditions or relating to the subject matter of these general terms and conditions, including liabilities arising in contract, in tort (including negligence) and for breach of statutory duty, except to the extent expressly provided otherwise in these general terms and conditions.` }} />
                <p className="mb-4 text-muted-foreground leading-relaxed" dangerouslySetInnerHTML={{ __html: `15.3 In respect of the services offered to you free of charge we will not be liable to you for any loss or damage of any nature whatsoever.` }} />
                <p className="mb-4 text-muted-foreground leading-relaxed" dangerouslySetInnerHTML={{ __html: `15.4 Our aggregate liability to you in respect of any contract to provide services to you under these general terms and conditions shall not exceed the total amount paid and payable to us under the contract. Each separate transaction on the marketplace shall constitute a separate contract for the purpose of this section 15.4.` }} />
                <p className="mb-4 text-muted-foreground leading-relaxed" dangerouslySetInnerHTML={{ __html: `15.5 Notwithstanding section 15.4 above, we will not be liable to you for any loss or damage of any nature, including in respect of:` }} />
                <p className="mb-4 text-muted-foreground leading-relaxed" dangerouslySetInnerHTML={{ __html: `15.5.1 any losses occasioned by any interruption or dysfunction to the website;` }} />
                <p className="mb-4 text-muted-foreground leading-relaxed" dangerouslySetInnerHTML={{ __html: `15.5.2 any losses arising out of any event or events beyond our reasonable control;` }} />
                <p className="mb-4 text-muted-foreground leading-relaxed" dangerouslySetInnerHTML={{ __html: `15.5.3 any business losses, including (without limitation) loss of or damage to profits, income, revenue, use, production, anticipated savings, business, contracts, commercial opportunities or goodwill;` }} />
                <p className="mb-4 text-muted-foreground leading-relaxed" dangerouslySetInnerHTML={{ __html: `15.5.4 any loss or corruption of any data, database or software; or` }} />
                <p className="mb-4 text-muted-foreground leading-relaxed" dangerouslySetInnerHTML={{ __html: `15.5.5 any special, indirect or consequential loss or damage.` }} />
                <p className="mb-4 text-muted-foreground leading-relaxed" dangerouslySetInnerHTML={{ __html: `15.6 We accept that we have an interest in limiting the personal liability of our officers and employees and, having regard to that interest, you acknowledge that we are a limited liability entity; you agree that you will not bring any claim personally against our officers or employees in respect of any losses you suffer in connection with the marketplace or these general terms and conditions (this will not limit or exclude the liability of the limited liability entity itself for the acts and omissions of our officers and employees).` }} />
                <p className="mb-4 text-muted-foreground leading-relaxed" dangerouslySetInnerHTML={{ __html: `15.7 Our marketplace includes hyperlinks to other websites owned and operated by third parties; such hyperlinks are not recommendations. We have no control over third party websites and their contents, and we accept no responsibility for them or for any loss or damage that may arise from your use of them.` }} />
                <h2 className="text-xl md:text-2xl font-bold text-foreground mt-8 mb-4">{`16. Indemnification`}</h2>
                <p className="mb-4 text-muted-foreground leading-relaxed" dangerouslySetInnerHTML={{ __html: `16.1 You hereby indemnify us, and undertake to keep us indemnified, against:` }} />
                <p className="mb-4 text-muted-foreground leading-relaxed" dangerouslySetInnerHTML={{ __html: `16.1.1 any and all losses, damages, costs, liabilities and expenses (including without limitation legal expenses and any amounts paid by us to any third party in settlement of a claim or dispute) incurred or suffered by us and arising directly or indirectly out of your use of our marketplace or any breach by you of any provision of these general terms and conditions or the Elddady codes, policies or guidelines; and` }} />
                <p className="mb-4 text-muted-foreground leading-relaxed" dangerouslySetInnerHTML={{ __html: `16.1.2 any VAT liability or other tax liability that we may incur in relation to any sale, supply or purchase made through our marketplace, where that liability arises out of your failure to pay, withhold, declare or register to pay any VAT or other tax properly due in any jurisdiction` }} />
                <h2 className="text-xl md:text-2xl font-bold text-foreground mt-8 mb-4">{`17. Breaches of these general terms and conditions`}</h2>
                <p className="mb-4 text-muted-foreground leading-relaxed" dangerouslySetInnerHTML={{ __html: `17.1 If we permit the registration of an account on our marketplace it will remain open indefinitely, subject to these general terms and conditions.` }} />
                <p className="mb-4 text-muted-foreground leading-relaxed" dangerouslySetInnerHTML={{ __html: `17.2 If you breach these general terms and conditions, or if we reasonably suspect that you have breached these general terms and conditions or any Elddady codes, policies or guidelines in any way we may:` }} />
                <p className="mb-4 text-muted-foreground leading-relaxed" dangerouslySetInnerHTML={{ __html: `17.2.1 temporarily suspend your access to our marketplace;` }} />
                <p className="mb-4 text-muted-foreground leading-relaxed" dangerouslySetInnerHTML={{ __html: `17.2.2 permanently prohibit you from accessing our marketplace;` }} />
                <p className="mb-4 text-muted-foreground leading-relaxed" dangerouslySetInnerHTML={{ __html: `17.2.3 block computers using your IP address from accessing our marketplace;` }} />
                <p className="mb-4 text-muted-foreground leading-relaxed" dangerouslySetInnerHTML={{ __html: `17.2.4 contact any or all of your internet service providers and request that they block your access to our marketplace;` }} />
                <p className="mb-4 text-muted-foreground leading-relaxed" dangerouslySetInnerHTML={{ __html: `17.2.5 suspend or delete your account on our marketplace; and/or` }} />
                <p className="mb-4 text-muted-foreground leading-relaxed" dangerouslySetInnerHTML={{ __html: `17.2.6 commence legal action against you, whether for breach of contract or otherwise.` }} />
                <p className="mb-4 text-muted-foreground leading-relaxed" dangerouslySetInnerHTML={{ __html: `17.3 Where we suspend, prohibit or block your access to our marketplace or a part of our marketplace you must not take any action to circumvent such suspension or prohibition or blocking (including without limitation creating and/or using a different account).` }} />
                <h2 className="text-xl md:text-2xl font-bold text-foreground mt-8 mb-4">{`18. Entire agreement`}</h2>
                <p className="mb-4 text-muted-foreground leading-relaxed" dangerouslySetInnerHTML={{ __html: `18.1 These general terms and conditions and the Elddady codes, policies and guidelines (and in respect of sellers the seller terms and conditions) shall constitute the entire agreement between you and us in relation to your use of our marketplace and shall supersede all previous agreements between you and us in relation to your use of our marketplace.` }} />
                <h2 className="text-xl md:text-2xl font-bold text-foreground mt-8 mb-4">{`19. Hierarchy`}</h2>
                <p className="mb-4 text-muted-foreground leading-relaxed" dangerouslySetInnerHTML={{ __html: `19.1 Should these general terms and conditions, the seller terms and conditions, and the Elddady codes, policies and guidelines be in conflict, these terms and conditions, the seller terms and conditions and the Elddady codes, policies and guidelines shall prevail in the order here stated.` }} />
                <h2 className="text-xl md:text-2xl font-bold text-foreground mt-8 mb-4">{`20. Variation`}</h2>
                <p className="mb-4 text-muted-foreground leading-relaxed" dangerouslySetInnerHTML={{ __html: `20.1 We may revise these general terms and conditions, the seller terms and conditions, and the Elddady codes, policies and guidelines from time to time.` }} />
                <p className="mb-4 text-muted-foreground leading-relaxed" dangerouslySetInnerHTML={{ __html: `20.2 The revised general terms and conditions shall apply from the date of publication on the marketplace.` }} />
                <h2 className="text-xl md:text-2xl font-bold text-foreground mt-8 mb-4">{`21. No waiver`}</h2>
                <p className="mb-4 text-muted-foreground leading-relaxed" dangerouslySetInnerHTML={{ __html: `21.1 No waiver of any breach of any provision of these general terms and conditions shall be construed as a further or continuing waiver of any other breach of that provision or any breach of any other provision of these general terms and conditions.` }} />
                <h2 className="text-xl md:text-2xl font-bold text-foreground mt-8 mb-4">{`22. Severability`}</h2>
                <p className="mb-4 text-muted-foreground leading-relaxed" dangerouslySetInnerHTML={{ __html: `22.1 If a provision of these general terms and conditions is determined by any court or other competent authority to be unlawful and/or unenforceable, the other provisions will continue in effect` }} />
                <p className="mb-4 text-muted-foreground leading-relaxed" dangerouslySetInnerHTML={{ __html: `22.2 If any unlawful and/or unenforceable provision of these general terms and conditions would be lawful or enforceable if part of it were deleted, that part will be deemed to be deleted, and the rest of the provision will continue in effect.` }} />
                <h2 className="text-xl md:text-2xl font-bold text-foreground mt-8 mb-4">{`23. Assignment`}</h2>
                <p className="mb-4 text-muted-foreground leading-relaxed" dangerouslySetInnerHTML={{ __html: `23.1 You hereby agree that we may assign, transfer, sub-contract or otherwise deal with our rights and/or obligations under these general terms and conditions.` }} />
                <p className="mb-4 text-muted-foreground leading-relaxed" dangerouslySetInnerHTML={{ __html: `23.2 You may not without our prior written consent assign, transfer, sub-contract or otherwise deal with any of your rights and/or obligations under these general terms and conditions.` }} />
                <h2 className="text-xl md:text-2xl font-bold text-foreground mt-8 mb-4">{`24. Third party rights`}</h2>
                <p className="mb-4 text-muted-foreground leading-relaxed" dangerouslySetInnerHTML={{ __html: `24.1 A contract under these general terms and conditions is for our benefit and your benefit, and is not intended to benefit or be enforceable by any third party.` }} />
                <p className="mb-4 text-muted-foreground leading-relaxed" dangerouslySetInnerHTML={{ __html: `24.2 The exercise of the parties' rights under a contract under these general terms and conditions is not subject to the consent of any third party.` }} />
                <h2 className="text-xl md:text-2xl font-bold text-foreground mt-8 mb-4">{`25. Law and jurisdiction`}</h2>
                <p className="mb-4 text-muted-foreground leading-relaxed" dangerouslySetInnerHTML={{ __html: `25.1 These general terms and conditions shall be governed by and construed in accordance with the laws of Kenya and applicable international laws for global operations.` }} />
                <p className="mb-4 text-muted-foreground leading-relaxed" dangerouslySetInnerHTML={{ __html: `25.2 Any disputes relating to these general terms and conditions shall be subject to the exclusive jurisdiction of the courts of Kenya.` }} />
                <h2 className="text-xl md:text-2xl font-bold text-foreground mt-8 mb-4">{`26. Our company details and notices`}</h2>
                <p className="mb-4 text-muted-foreground leading-relaxed" dangerouslySetInnerHTML={{ __html: `26.1 You can contact us by using the contact details provided on our website.` }} />
                <p className="mb-4 text-muted-foreground leading-relaxed" dangerouslySetInnerHTML={{ __html: `26.2 You may contact our sellers for after-sales queries, including any disputes, by requesting their contact details, including the full legal name of the Seller and where applicable the shop name, from Elddady in accordance with the Dispute Resolution Policy, pursuant to which Elddady shall be obliged to ensure that the seller is identifiable and clearly linked to the transaction in question.` }} />
                <p className="mb-4 text-muted-foreground leading-relaxed" dangerouslySetInnerHTML={{ __html: `26.3 You consent to receive notices electronically from us. We may provide all communications and information related to your use of the marketplace in electronic format, either by posting to our website or application, or by email to the email address on your account. All such communications will be deemed to be notices in writing and received by and properly given to you.` }} />
            </div>
        </div>
    );
};

export default TermsAndConditionsPage;